name: Sync Codeberg to GitHub

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间凌晨 0 点同步一次
  workflow_dispatch:    # 允许手动触发同步

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository (Codeberg)
        run: |
          git clone --mirror https://codeberg.org/forgejo/forgejo.git source-repo

      - name: Push to GitHub Repository
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          cd source-repo
          git push --mirror https://x-access-token:${GH_PAT}@github.com/tameslabs/forgit.git

      - name: Cleanup
        run: |
          rm -rf source-repo
